// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bacnskcizgzcrqusqalu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhY25za2Npemd6Y3JxdXNxYWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTQ4ODAsImV4cCI6MjA1ODczMDg4MH0.Nc2jUUB6OlzEmMmUz7h7Ns3q1e-TIH2r-oLcLfJjp9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);